spring:
  datasource:
    url: jdbc:postgresql://localhost:54432/db_y_lab
    username: user_123
    password: pass_123
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 5

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.xml
    db.liquibaseSchema: liquibase_schema
    db.appSchema: marketplace

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

server:
  port: 8080